spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://8.130.49.88:3307/sqlfather
    username: root
    password: yaoshuaixiang
mybatis-plus:
  configuration:
    # 生产环境关闭日志
    log-impl: ''